spring:
  application:
    name: Shop
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

key:
  access: Tmu6OXdunqE7e4tVVWrJF3OdlxuJGcmvZt8yjSJqNXU=
  refresh: BMpbW0LGCu9wEjeRCiomM6tIvHFncb4kplb4yfHELCU=

messages:
  hello: Hello from Digital ocean!

